repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: [ "--disable", "MD013" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: conventional-commits
        name: conventional commits
        entry: "grep -qP '^(feat|fix|docs|refactor|test|chore|ci|style|perf|build|revert)(\\(.+\\))?: .+'"
        language: system
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
      - id: name-tests-test
      - id: pretty-format-json
        args: [ "--autofix", "--indent=2" ]
      - id: trailing-whitespace
